# Uncomment the next line to define a global platform for your project
# platform :ios, '16.2'

target 'Stories' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Stories
  pod 'TagListView', '~> 1.0'

  target 'StoriesTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
