platform :ios, '16.0'

target 'Stories' do
  use_frameworks!

  # Pods for Stories
  pod 'ViewAnimator', '3.1.0'
  pod 'TagListView', '~> 1.0'
  pod 'RxSwift', '6.5.0'
  pod 'RxCocoa', '6.5.0'
      
  target 'StoriesTests' do
    inherit! :search_paths
    pod 'RxBlocking', '6.5.0'
    pod 'RxTest', '6.5.0'
  end

end
